config/routes.rb
Rails.application.routes.draw do
  resources :notes, path: '/'

  root to: 'notes#index'

  post 'set_timezone', to: 'application#set_timezone'
  
  post '/set_locale', to: 'locales#update', as: 'set_locale'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  validates :body, presence: true
  
  validates :title, presence: true, uniqueness: { message: ->(object, data) { I18n.t('activerecord.errors.messages.taken') } }
        
  scope :search_by_title_or_body, ->(query) { where("title LIKE ? OR body LIKE ?", "%#{query}%", "%#{query}%") }

  def self.search_by_title(keywords)
    keywords.split.reduce(self) do |acc, word|
      acc.where "title LIKE ? ESCAPE '\\'", "%#{escape_sql_pattern word}%"
    end
  end

  private

  def self.escape_sql_pattern(pattern)
    pattern.gsub(/[%_\\]/, '\\\\\\&')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_user_timezone
  before_action :set_locale
  
  def set_user_timezone
    if session[:timezone]
      Time.zone = session[:timezone]  # Set the time zone from the session
    else
      Time.zone = 'UTC'  # Default to UTC if no timezone is set
    end
  end
  
  # This action will be called by the AJAX request to set the user's time zone
  def set_timezone
    session[:timezone] = params[:timezone]  # Store the time zone in the session
    render json: { status: 'success' }  # Respond with success message
  end

  def set_locale
    I18n.locale = session[:locale] || I18n.default_locale
  end
end

app/controllers/locales_controller.rb
class LocalesController < ApplicationController
    def update
      locale = params[:locale]
      if I18n.available_locales.map(&:to_s).include?(locale)
        session[:locale] = locale
      end
      redirect_back(fallback_location: root_path)
    end
  end
  

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]

  def index
    session[:filters] ||= {}
  
    @filters = params[:filters]&.to_unsafe_h&.symbolize_keys
  
    if @filters
      session[:filters].merge!(@filters)
    end
  
    @notes = if @filters.present? && @filters[:title].present?
        Note.search_by_title_or_body(@filters[:title])
    elsif session.dig('filters', 'title').present?
      Note.search_by_title_or_body(session.dig('filters', 'title'))
    else
      Note.all
    end

    sort_by = if @filters.present? && @filters[:sort_by].present?
        @filters[:sort_by]
    else
      session.dig('filters', 'sort_by')
    end

    case sort_by
    when 'created_at_asc'
      @notes = @notes.order(created_at: :asc)
    when 'created_at_desc'
      @notes = @notes.order(created_at: :desc)
    when 'title_asc'
      @notes = @notes.order(title: :asc)
    when 'title_desc'
      @notes = @notes.order(title: :desc)
    else
      @notes = @notes.order(created_at: :desc)
    end
  
    @notes = @notes.group_by { |note| note.created_at.strftime("%B") }
  end  

  def show
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def create
    @note = Note.new(note_params)
  
    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: I18n.t('notices.note_created') }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end  

  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: I18n.t('notices.note_updated') }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: I18n.t('notices.note_destroyed') }
      format.json { head :no_content }
    end
  end
  
  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_as_localtime(datetime, format = '')
    format = "%d/%b/%Y, %H:%M:%S" unless format.present?
    datetime.localtime.strftime format
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title><%= I18n.t('navbar.title') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <div class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <%= link_to notes_path, class: 'brand-logo center' do %>
                <%= I18n.t('navbar.title') %>
                <% end %>
                <div class="right row" style="display:flex; align-items: center;">
                    <div class="col s6">
                        <%= form_with(url: set_locale_path, method: :post, local: true) do %>
                        <%=
                            select_tag 'locale',
                            options_for_select([['English', 'en'], ['Español', 'es']],
                            I18n.locale),
                            class: 'custom-dropdown',
                            onchange: 'this.form.submit();'
                        %>
                        <% end %>
                    </div>
                    <div class="col s6">
                        <button id="dark-mode-toggle" class="btn-floating btn-large" style="margin: 0px 5px;">
                            <i class="material-icons">brightness_2</i>
                        </button>
                    </div>
                </div>
            </div>
        </nav>
    </div>
    <div class="container">
        <%= yield %>
    </div>
    <%= javascript_pack_tag 'timezone' %>
    <%= javascript_pack_tag 'darkmode', defer: true %>
</body>

</html>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h5><%= pluralize(note.errors.count, I18n.t('errors.template.header.one'), I18n.t('errors.template.header.other')) %> <%= I18n.t('errors.template.body') %></h5>

      <ul>
        <% note.errors.full_messages.each do |message| %>
          <li>&bull; <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row" style="margin-top: 7mm">
    <div class="input-field col s12">
      <%= form.text_field :title, autofocus: true %>
      <%= form.label :title, I18n.t('form.labels.title') %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col s12">
      <%= form.text_area :body, class: 'materialize-textarea' %>
      <%= form.label :body, I18n.t('form.labels.body') %>
    </div>
  </div>

  <div class="row">
    <div class="col s12 right-align">
      <button class="btn-flat waves-effect waves-light" type="submit">
        <%= material_icon.send %>
      </button>
    </div>
  </div>
<% end %>

app/views/notes/edit.html.erb
<%= render 'form', note: @note %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <%= form_for :filters, html: { class: 'input-field col s12' }, method: 'get' do |f| %>
    <%= material_icon.search.css_class('prefix') %>
    <%= 
        f.text_field :title, autofocus: true, placeholder: I18n.t('placeholders.search_by_title'),
        value: (@filters.present? && @filters[:title].present?) ? @filters[:title] : session.dig('filters', 'title')
    %>
    <%= f.select :sort_by, options_for_select(
    [
      [I18n.t('filters.sort_by.date_ascending'), 'created_at_asc'],
      [I18n.t('filters.sort_by.date_descending'), 'created_at_desc'],
      [I18n.t('filters.sort_by.az'), 'title_asc'],
      [I18n.t('filters.sort_by.za'), 'title_desc']
    ],
    selected: (@filters.present? && @filters[:sort_by].present?) ? @filters[:sort_by] : session.dig('filters', 'sort_by')) %>
    <% end %>

    <div id="notes-container">
        <% @notes.each do |month, notes| %>
        <div class="col s12">
            <h4><%= I18n.t("date.month_names.#{month.downcase}") %></h4>
        </div>
        <% notes.each do |note| %>
        <%= link_to note_path(note) do %>
        <div class="col s12 m6 l4">
            <div class="card">
                <div class="card-content black-text">
                    <span class="card-title">
                        <%= note.title %>
                        <span class="right" style="font-size: 50%">
                            <%= note.created_at.in_time_zone(session[:timezone]).strftime("%d/%b/%Y, %H:%M:%S") %>
                        </span>
                    </span>
                </div>
            </div>
        </div>
        <% end %>
        <% end %>
        <% end %>
    </div>
</div>
<div class="fixed-action-btn">
    <%= 
        link_to new_note_path,
        class: 'btn-floating btn-large pulse tooltipped',
        data: { position: 'left', tooltip: I18n.t('tooltips.new_note') } do
    %>
    <%= material_icon.add %>
    <% end %>
    <%= javascript_pack_tag 'tooltip' %>
</div>

<%= javascript_pack_tag 'filter' %>

app/views/notes/new.html.erb
<%= render 'form', note: @note %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          <%= @note.title %>
          <span class="right" style="font-size: 50%">
            <%= @note.created_at.in_time_zone(session[:timezone]).strftime("%d/%b/%Y, %H:%M:%S") %>
          </span>
        </span>
        <p style="white-space: pre-line"><%= @note.body %></p>
      </div>
      <div class="card-action">
        <%= link_to @note, title: 'Delete', method: :delete, data: { confirm: I18n.t('confirmations.are_you_sure') }, class: 'black-text' do %>
          <%= material_icon.delete %>
        <% end %>

        <%= link_to edit_note_path(@note), title: 'Edit', class: 'black-text right' do %>
          <%= material_icon.mode_edit %>
        <% end %>
      </div>
    </div>
  </div>
</div>